CREATE TABLE IF NOT EXISTS warehouse.dim_radio_show_host
(
    dim_radio_show_host_key INT PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1,
    fact_radio_show_key      INT     NOT NULL FOREIGN KEY REFERENCES WAREHOUSE.fact_radio_show (FACT_SHOW_KEY),
    dim_radio_host_key      INT     NOT NULL FOREIGN KEY REFERENCES WAREHOUSE.dim_radio_host (DIM_HOST_KEY),
    DW_CREATE_DATE    TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER    VARCHAR NOT NULL DEFAULT CURRENT_USER(),
    DW_UPDATE_DATE    TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_USER    VARCHAR NOT NULL DEFAULT CURRENT_USER()
);
