CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_HOST
(
    DIM_HOST_KEY   INT PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1,
    HOST_ID        INT     NOT NULL,
    NAME           VARCHAR NULL,
    URI            VARCHAR NULL,
    IMAGE_URI      VARCHAR NULL,

    THUMBNAIL_URI  VARCHAR NULL,
    IS_ACTIVE      BOOLEAN NULL,
    DW_ACTIVE      BOOLEAN          DEFAULT TRUE NOT NULL,
    DW_FROM_DATE   TIMESTAMPLTZ,
    DW_TO_DATE     TIMESTAMPLTZ     DEFAULT CAST('2099-12-31 00:00:00' AS TIMESTAMP_LTZ(9)) NOT NULL,
    DW_CREATE_DATE TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER VARCHAR NOT NULL DEFAULT CURRENT_USER(),
    DW_UPDATE_DATE TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_USER VARCHAR NOT NULL DEFAULT CURRENT_USER()
);
