CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_SHOW_HOST
(
    DIM_SHOW_HOST_KEY INT PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1,
    DIM_SHOW_KEY      INT     NOT NULL FOREIGN KEY REFERENCES WAREHOUSE.DIM_SHOW (DIM_SHOW_KEY),
    DIM_HOST_KEY      INT     NOT NULL FOREIGN KEY REFERENCES WAREHOUSE.DIM_HOST (DIM_HOST_KEY),
    DW_CREATE_DATE    TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER    VARCHAR NOT NULL DEFAULT CURRENT_USER(),
    DW_UPDATE_DATE    TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_USER    VARCHAR NOT NULL DEFAULT CURRENT_USER()
);
