-- Created by ChatGPT
CREATE TABLE IF NOT EXISTS WAREHOUSE.DIM_RADIO_STATION
(
    DIM_STATION_KEY INT PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1,

    station_id      INT UNIQUE NOT NULL,
    station_name    VARCHAR,
    frequency       FLOAT,
    location        VARCHAR,
    owner           VARCHAR,
    format          VARCHAR,
    api             VARCHAR,
    uri             VARCHAR,
    IS_ACTIVE       BOOLEAN    NULL,
    DW_ACTIVE       BOOLEAN             DEFAULT TRUE NOT NULL,
    DW_FROM_DATE    TIMESTAMPLTZ,
    DW_TO_DATE      TIMESTAMPLTZ        DEFAULT CAST('2099-12-31 00:00:00' AS TIMESTAMP_LTZ(9)) NOT NULL,
    DW_CREATE_DATE  TIMESTAMPTZ         DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER  VARCHAR    NOT NULL DEFAULT CURRENT_USER(),
    DW_UPDATE_DATE  TIMESTAMPTZ         DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_USER  VARCHAR    NOT NULL DEFAULT CURRENT_USER()
);
