CREATE TABLE IF NOT EXISTS WAREHOUSE.FACT_PLAYLIST
(
    FACT_PLAYLIST_KEY INT PRIMARY KEY IDENTITY (1,1),
    DIM_SHOW_KEY      INT           NOT NULL FOREIGN KEY REFERENCES WAREHOUSE.DIM_SHOW (DIM_SHOW_KEY),
    DIM_STATION_KEY   INT           NOT NULL FOREIGN KEY REFERENCES WAREHOUSE.DIM_STATION (DIM_STATION_KEY),

    LOAD_ID           INT           NOT NULL,
    PLAYLIST_ID       INT UNIQUE    NOT NULL,
    PLAY_TYPE         STRING        NULL,
    AIRDATE           TIMESTAMP_LTZ NOT NULL,
    ALBUM             STRING        NULL,
    ARTIST            STRING        NULL,
    SONG              STRING        NULL,

    COMMENT           VARCHAR,
    IMAGE_URI         VARCHAR,
    LABELS            VARIANT,
    RELEASE_DATE      VARCHAR,
    DW_CREATE_DATE    TIMESTAMPTZ            DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER    VARCHAR       NOT NULL DEFAULT CURRENT_USER(),
    DW_UPDATE_DATE    TIMESTAMPTZ            DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_USER    VARCHAR       NOT NULL DEFAULT CURRENT_USER(),
    FOREIGN KEY (DIM_SHOW_KEY) REFERENCES WAREHOUSE.DIM_SHOW (DIM_SHOW_KEY)
);

