metabase:
	docker run -d -p 3000:3000 --name metabase metabase/metabase

postgres:
	docker run --name owlmtn-postgres -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} -d postgres


docker:
	brew install docker