# Note that you need to initialize the Zillow venv for this.
# We don't mix our requirements in this dojo.

zillow_rental_rate_forecast:
	python python/zillow_rental_rate_forecase.py

scrape:
	python python/zillow_scraper.py