helm-upgrade:
	helm upgrade --install airflow apache-airflow/airflow --namespace airflow --create-namespace

apache-repo:
	helm repo add apache-airflow https://airflow.apache.org

install-helm:
	brew install helm