run-spark:
	python3 python/kexp_spark_local.py

upgrade-pyspark:
	pip install pyspark --upgrade

upgrade-delta:
	pip install delta-spark --upgrade

upgrade: upgrade-pyspark upgrade-delta



version:
	pyspark --version
