!set variable_substitution=true;
CREATE USER IF NOT EXISTS "&{TF_USER}" password='&{TF_PASSWORD}' RSA_PUBLIC_KEY='&{TF_PUBLIC_KEY}'
    DEFAULT_ROLE=ACCOUNTADMIN MUST_CHANGE_PASSWORD=FALSE;
CREATE ROLE IF NOT EXISTS ROLE_&{TF_USER};
GRANT ROLE SYSADMIN TO ROLE "tf-snow";
GRANT ROLE SECURITYADMIN TO ROLE "tf-snow";
ALTER USER "tf-snow" set DEFAULT_ROLE=ACCOUNTADMIN;