!set variable_substitution=true;
use role ACCOUNTADMIN;
CREATE USER IF NOT EXISTS "&{TF_USER}" password='&{TF_PASSWORD}' RSA_PUBLIC_KEY='&{TF_PUBLIC_KEY}'
    DEFAULT_ROLE=ACCOUNTADMIN MUST_CHANGE_PASSWORD=FALSE;
CREATE ROLE IF NOT EXISTS "ROLE_&{TF_USER}";
GRANT ROLE SYSADMIN TO ROLE "ROLE_&{TF_USER}";
GRANT ROLE SECURITYADMIN TO ROLE "ROLE_&{TF_USER}";
GRANT ROLE SECURITYADMIN TO ROLE "ROLE_&{TF_USER}";
GRANT ROLE ACCOUNTADMIN TO ROLE "ROLE_&{TF_USER}";
GRANT ROLE "ROLE_&{TF_USER}" to user "&{TF_USER}";
ALTER USER "&{TF_USER}" set DEFAULT_ROLE="ROLE_&{TF_USER}";
