AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cloudformation Template to build out the KEXP Sync AWS Environment

Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Function:
    Runtime: python3.7
    MemorySize: 512

Parameters:
  RestApiName:
    Type: String

  ExportBucketArn:
    Type: String

  ExportBucket:
    Type: String

  ExportStage:
    Type: String

  LayerAws:
    Type: String

  LayerLake:
    Type: String

Resources:
  DefaultLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "AllowMetricAdd"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "cloudwatch:PutMetricData"
                Resource: "*"

        - PolicyName: "AllowInvoke"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "lambda:InvokeFunction"
                Resource: "*"

        - PolicyName: "AllowExportBucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource:
                  - !Ref ExportBucketArn
                  - !Join ["/", [!Ref ExportBucketArn, '*']]

        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${RestApiName}:*"
          PolicyName: "lambda"

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  LambdaSyncKexpSnowflake:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: kexp_lambda_function.sync_kexp_s3
      CodeUri: .
      Description: >-
        Synchronize the KEXP Playlist Data to S3 Data Lake
      Timeout: 900

      Role: !GetAtt DefaultLambdaRole.Arn

      Layers:
        - !Ref LayerAws
        - !Ref LayerLake

      Environment:
        Variables:
          ExportBucket: !Ref ExportBucket
          ExportStage: !Ref ExportStage

  KexpSyncEventIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                  - Fn::Sub: "events.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: StateMachineExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "states:StartExecution"
                Resource:
                  - !Ref SyncKexpPipeline

  SyncKexpPipeline:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Save the current KEXP Playlist Resutls to S3 Data Lake",
              "StartAt": "KexpGetcurrent",
              "States": {
                "KexpGetcurrent": {
                  "Type": "Task",
                  "Resource": "${KexpSyncS3Arn}",
                  "End": true
                }
              }
            }
          - {KexpSyncS3Arn: !GetAtt [ LambdaSyncKexpSnowflake, Arn ]}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  ScheduledKexpSync:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Scheduled event to trigger SyncKexpPipeline state machine at 40 past"
      ScheduleExpression: cron(40 8 ? * MON-SUN *)
      State: "ENABLED"
      Targets:
        -
          Arn: !Ref SyncKexpPipeline
          Id: !GetAtt SyncKexpPipeline.Name
          RoleArn: !GetAtt KexpSyncEventIAMRole.Arn