zillow_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1  # Use "localhost" or your local IP
      port: 5432       # Default PostgreSQL port
      user: "{{ env_var('PG_USER') }}"
      password: "{{ env_var('PG_PASSWORD') }}"
      dbname: postgres
      schema: public   # Replace with your desired schema
      threads: 4       # Adjust the number of threads based on your system
      keepalives_idle: 0  # Optional: set to avoid connection timeouts
