create table if not exists STAGE.COPY_STATISTICS
(
    TABLE_NAME VARCHAR(12),
    QUERY_ID   VARCHAR,
    RESULT     VARIANT,
    DW_CREATE_DATE     TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER     VARCHAR NOT NULL DEFAULT CURRENT_USER()
);

