CREATE TABLE IF NOT EXISTS STAGE.CMS_PROVIDER
(
    NPI                STRING,
    IND_PAC_ID         STRING,
    IND_ENRL_ID        STRING,
    LST_NM             STRING,
    FRST_NM            STRING,
    MID_NM             STRING,
    SUFF               STRING,
    GNDR               STRING,
    CRED               STRING,
    MED_SCH            STRING,
    GRD_YR             INTEGER,
    PRI_SPEC           STRING,
    SEC_SPEC_1         STRING,
    SEC_SPEC_2         STRING,
    SEC_SPEC_3         STRING,
    SEC_SPEC_4         STRING,
    SEC_SPEC_ALL       STRING,
    ORG_NM             STRING,
    ORG_PAC_ID         STRING,
    NUM_ORG_MEM        STRING,
    ADR_LN_1           STRING,
    ADR_LN_2           STRING,
    LN_2_SPRS          STRING,
    CTY                STRING,
    ST                 STRING,
    ZIP                STRING,
    PHN_NUMBR          STRING,
    HOSP_AFL_1         STRING,
    HOSP_AFL_LBN_1     STRING,
    HOSP_AFL_2         STRING,
    HOSP_AFL_LBN_2     STRING,
    HOSP_AFL_3         STRING,
    HOSP_AFL_LBN_3     STRING,
    HOSP_AFL_4         STRING,
    HOSP_AFL_LBN_4     STRING,
    HOSP_AFL_5         STRING,
    HOSP_AFL_LBN_5     STRING,
    IND_ASSGN          STRING,
    GRP_ASSGN          STRING,
    ADRS_ID            STRING,
    DW_FILENAME        STRING  NOT NULL,
    DW_FILE_ROW_NUMBER INTEGER NOT NULL,
    DW_IS_ACTIVE       BOOLEAN          DEFAULT TRUE,
    DW_MODIFIED_DATE   TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_MODIFIED_USER   VARCHAR NOT NULL DEFAULT CURRENT_USER(),
    DW_CREATE_DATE     TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER     VARCHAR NOT NULL DEFAULT CURRENT_USER()
)