create or replace table ADMIN.SNOWFLAKE_LOGIN_HISTORY
(
	EVENT_TIMESTAMP TIMESTAMPLTZ(3),
	EVENT_ID NUMBER,
	EVENT_TYPE VARCHAR,
	USER_NAME VARCHAR,
	CLIENT_IP VARCHAR,
	REPORTED_CLIENT_TYPE VARCHAR,
	REPORTED_CLIENT_VERSION VARCHAR,
	FIRST_AUTHENTICATION_FACTOR VARCHAR,
	SECOND_AUTHENTICATION_FACTOR VARCHAR,
	IS_SUCCESS VARCHAR(3),
	ERROR_CODE NUMBER,
	ERROR_MESSAGE VARCHAR,
	RELATED_EVENT_ID NUMBER,
	DW_CREATE_DATE TIMESTAMPLTZ not null default current_timestamp(),
	DW_CREATED_BY VARCHAR not null default current_user()
);





