CREATE or replace TASK ADMIN.APPEND_SNOWFLAKE_LOGIN_HISTORY
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON * * * * SUN-SAT America/New_York'
AS
    call ADMIN.APPEND_SNOWFLAKE_LOGIN_HISTORY();

use schema admin;

show tasks;

alter task admin.APPEND_SNOWFLAKE_LOGIN_HISTORY resume;