create or replace table ADMIN.SNOWFLAKE_USERS
(
	"name" VARCHAR,
	"created_on" VARCHAR,
	"login_name" VARCHAR,
	"display_name" VARCHAR,
	"first_name" VARCHAR,
	"last_name" VARCHAR,
	"email" VARCHAR,
	"mins_to_unlock" VARCHAR,
	"days_to_expiry" VARCHAR,
	"comment" VARCHAR,
	"disabled" VARCHAR,
	"must_change_password" VARCHAR,
	"snowflake_lock" VARCHAR,
	"default_warehouse" VARCHAR,
	"default_namespace" VARCHAR,
	"default_role" VARCHAR,
	"ext_authn_duo" VARCHAR,
	"ext_authn_uid" VARCHAR,
	"mins_to_bypass_mfa" VARCHAR,
	"owner" VARCHAR,
	"last_success_login" VARCHAR,
	"expires_at_time" VARCHAR,
	"locked_until_time" VARCHAR,
	"has_password" VARCHAR,
	"has_rsa_public_key" VARCHAR,
	DW_CREATED_DATE TIMESTAMPLTZ default CURRENT_TIMESTAMP() not null,
	DW_CREATED_BY VARCHAR(100) default CURRENT_USER() not null
);
