CREATE or replace TASK ADMIN.CREATE_SNAPSHOT_GRANTS_OF_ROLE
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 9-17 * * SUN-SAT America/New_York'
AS
call ADMIN.SNAPSHOT_GRANTS_OF_ROLE();


select *
from admin.SNOWFLAKE_GRANTS_OF_ROLE;
