call ADMIN.SNAPSHOT_USERS();
call ADMIN.SNAPSHOT_USER_GRANT();
call ADMIN.SNAPSHOT_USER_NETWORK_POLICY();
call ADMIN.APPEND_SNOWFLAKE_LOGIN_HISTORY();
call ADMIN.SNAPSHOT_ROLES();
call ADMIN.SNAPSHOT_ROLE_GRANT();
call ADMIN.SNAPSHOT_GRANTS_OF_ROLE();

