create table if not exists WAREHOUSE.DIM_CALENDAR
(
    DIM_CALENDAR_KEY INT primary key autoincrement start 1 increment 1,
    DATE         DATE,
    YEAR         NUMBER(4),
    MONTH        NUMBER(2),
    MONTH_NAME   VARCHAR(3),
    DAY_OF_MON   NUMBER(2),
    DAY_OF_WEEK  NUMBER(2),
    WEEK_OF_YEAR NUMBER(2),
    DAY_OF_YEAR  NUMBER(4),
    WEEKDAY      NUMBER(2),
    DAYNAME      VARCHAR(3),
    DW_CREATE_DATE TIMESTAMPTZ            DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER VARCHAR       NOT NULL DEFAULT CURRENT_USER(),
    DW_UPDATE_DATE TIMESTAMPTZ            DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_USER VARCHAR       NOT NULL DEFAULT CURRENT_USER()
);

