create table if not exists ANALYTICS.FAVORITE_HOST(
    FAVORITE_HOST_KEY   INT PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1,
    DIM_HOST_KEY INT FOREIGN KEY REFERENCES WAREHOUSE.DIM_HOST(DIM_HOST_KEY),
    FAVORITE_RANK INT default ANALYTICS.FAVORITE_SEQUENCE.nextval
)