create table if not exists ANALYTICS.HOST_SUMMARY(
    FAVORITE_HOST_KEY   INT PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1,
    DIM_HOST_KEY INT FOREIGN KEY REFERENCES WAREHOUSE.DIM_HOST(DIM_HOST_KEY),
    DIM_CALENDAR_KEY INT FOREIGN KEY REFERENCES WAREHOUSE.DIM_CALENDAR(DIM_CALENDAR_KEY),
    PLAYLIST_COUNT INT,
    LISTENER_FAVORITE_RANK INT,
    TRANSACTION_ID INT default ANALYTICS.TRANSACTION_SEQUENCE.nextval,
    DW_CREATE_DATE TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_CREATE_USER VARCHAR NOT NULL DEFAULT CURRENT_USER(),
    DW_UPDATE_DATE TIMESTAMPTZ      DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_USER VARCHAR NOT NULL DEFAULT CURRENT_USER()
)