select count(*)
from  STAGE.STREAM_IMPORT_KEXP_PLAYLIST_CDC;

select count(*)
from  STAGE.STREAM_IMPORT_KEXP_SHOW_CDC;

select PROGRAM_NAME
    , PROGRAM_TAGS
--     , HOST_NAMES
    , TAGLINE
--     , START_TIME
from  STAGE.STREAM_IMPORT_KEXP_SHOW_CDC;

select count(*) / 1e6
from STAGE.IMPORT_KEXP_PLAYLIST;

select ARTIST, SONG, ALBUM, metadata$ACTION, metadata$ISUPDATE
from  STAGE.STREAM_IMPORT_KEXP_PLAYLIST_CDC;

select *
from  STAGE.STREAM_IMPORT_KEXP_PLAYLIST_CDC;


select *
from WAREHOUSE.DIM_KEXP_SHOW
order by start_time desc;

select *
from WAREHOUSE.FACT_KEXP_PLAYLIST
order by AIRDATE desc;